import Head from "next/head";
import { Inter } from "next/font/google";
// import test from "../tailwind/"
// import "@/tailwind/output.css";
import Pricing from "@/components/home/Pricing";
import Quote from "@/components/home/Quote";
import HeroLanding from "@/components/home/HeroLanding";
import BusinessPartners from "@/components/home/BusinessPartners";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Teckiee | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <HeroLanding />
        <Quote />
        <Pricing />
        <BusinessPartners />
      </main>
    </>
  );
}
/*
display:flex;
justify-content:center;
width:100%
*/
